services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - keycloak
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: ['start-dev','--import-realm']
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8089:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes/
      - ./keycloak/data/import:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - keycloak_network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge
